<?php namespace ProcessWire;

class ProcessListerSelector extends Process implements Module, ConfigurableModule {

	public static function getModuleInfo() {
		return array(
			'title' => 'Lister Selector',
			'summary' => 'Use a selector string to list items with Lister/ListerPro.',
			'version' => '0.1.4',
			'author' => 'Robin Sallis',
			'href' => 'https://github.com/Toutouwai/ListerSelector',
			'icon' => 'search-plus',
			'useNavJSON' => true,
			'requires' => 'ProcessWire>=3.0.0, PHP>=5.4.0',
			'page' => array(
				'parent' => 'setup',
				'name' => 'lister-selector',
				'title' => 'Lister Selector',
			),
			'permission' => 'lister-selector',
			'permissions' => array(
				'lister-selector' => 'Use the Lister Selector module'
			),
		);
	}

	public $lister;

	/**
	 * Init
	 */
	public function init() {
		parent::init();
		$this->addHookBefore('InputfieldForm::render', $this, 'beforeFormRender');
		$this->addHookAfter('ProcessPageLister::renderedExtras', $this, 'afterRenderedExtras');
		$this->addHookAfter('ProcessPageLister::getSelector', $this, 'afterGetSelector');
		$this->addHookAfter('ProcessPageLister::renderResults', $this, 'afterRenderResults');

		// Define lister
		$modules = $this->wire()->modules;
		if($modules->isInstalled('ProcessPageListerPro')) {
			/* @var ProcessPageListerPro $lister */
			$lister = $modules->get('ProcessPageListerPro');
			$lister->allowActions = $this->enabled_actions ?: [];
			$lister->viewMode = $this->view_mode;
			$lister->editMode = $this->edit_mode;
		} else {
			/* @var ProcessPageLister $lister */
			$lister = $modules->get('ProcessPageLister');
		}
		$lister->allowBookmarks = false;
		$lister->defaultSelector = '';
		$this->lister = $lister;
	}

	/**
	 * Construct
	 */
	public function __construct() {
		parent::__construct();
		$this->edit_mode = ProcessPageLister::windowModeNone;
		$this->view_mode = ProcessPageLister::windowModeNone;
	}

	/**
	 * Before InputfieldForm::render
	 * Prevent filters form from being a WireTab
	 *
	 * @param HookEvent $event
	 */
	protected function beforeFormRender(HookEvent $event) {
		/* @var InputfieldForm $form */
		$form = $event->object;
		if($form->id !== 'ProcessListerFiltersForm') return;
		$form->removeClass('WireTab'); // Prevent form from being a WireTab
	}

	/**
	 * After ProcessPageLister::renderedExtras
	 * Add "Selector" tab
	 *
	 * @param HookEvent $event
	 */
	protected function afterRenderedExtras(HookEvent $event) {
		/* @var ProcessPageLister $lister */
		$lister = $event->object;
		$wrapper = new InputfieldWrapper();
		$session_selector = $lister->sessionGet('selector');
		/* @var InputfieldText $f */
		$f = $this->wire()->modules->get('InputfieldText');
		$f->name = 'ls_selector';
		$f->id = 'ls_selector';
		$f->label = $this->_('Selector string');
		if($session_selector) $f->value = $session_selector;
		$wrapper->add($f);
		$wrapper_render = $wrapper->render();
		$out = "<div id='ListerSelectorTab' title='Selector' class='WireTab'>$wrapper_render</div>";
		$event->return = $out . $event->return;
	}

	/**
	 * After ProcessPageLister::getSelector
	 * Replace processed selector with original saved to session
	 *
	 * @param HookEvent $event
	 */
	protected function afterGetSelector(HookEvent $event) {
		/* @var ProcessPageLister $lister */
		$lister = $event->object;
		$limit = $event->arguments(0);
		$selector_str = $lister->sessionGet('selector');
		// Set limit when supplied as an argument
		if($limit !== null) {
			$selectors = new Selectors($selector_str);
			$s_limit = $selectors->get("field=limit");
			if($s_limit) {
				$s_limit->value = $limit;
			} else {
				$s_limit = new SelectorEqual('limit', $limit);
				$selectors->add($s_limit);
			};
			if($s_limit) $selectors->remove($s_limit);
			$selector_str = (string) $selectors;
		}
		$event->return = $selector_str;
	}

	/**
	 * After ProcessPageLister::renderResults
	 * Add bookmark string for easy copy/paste
	 *
	 * @param HookEvent $event
	 */
	protected function afterRenderResults(HookEvent $event) {
		/* @var ProcessPageLister $lister */
		$lister = $event->object;
		$selector = $lister->sessionGet('selector');
		// Remove the default limit because it's not needed for a bookmark
		$selector = str_replace([', limit=25', 'limit=25, '], '', $selector);
		$columns = $lister->columns;
		$bookmark_label = $this->_('Bookmark string...');
		$your_label = $this->_('Your label');
		$bookmark = "{$bookmark_label}<br>{$your_label}:{$selector}";
		if($columns) {
			$columns_string = implode(',', $columns);
			$bookmark .= ":{$columns_string}";
		}
		$event->return .= "<p class='notes'>$bookmark</p>";
	}

	/**
	 * Execute
	 *
	 * @return string
	 */
	public function ___execute() {
		$config = $this->wire()->config;
		$out = '';

		// Add config icon: only for superuser
		if($this->wire()->user->isSuperuser() && !$config->ajax) {
			$config_tooltip = $this->_('Configure Lister Selector');
			$admin_url = $config->urls->admin;
			$out = "<a id='ListerSelectorConfig' href='{$admin_url}module/edit?name=ProcessListerSelector' uk-tooltip='title:$config_tooltip; pos:top-left' title='$config_tooltip'><i class='fa fa-fw fa-cog ui-priority-secondary'></i></a>";
		}

		// Render Lister
		/* @var ProcessPageLister|ProcessPageListerPro $lister */
		$lister = $this->lister;
		$bookmark = $this->wire()->input->get->text('bm');
		if($bookmark) {
			// Get pieces from decoded bookmark
			$pieces = explode(':', $this->urlSafeBase64Decode($bookmark));
			$pieces = array_filter(array_map('trim', $pieces));
			// Assign to variables
			list($selector, $columns_string) = array_pad($pieces, 2, null);
			// Set selector
			if($selector) $lister->sessionSet('selector', $selector);
			// Set columns if any
			if($columns_string) {
				$columns = explode(',', $columns_string);
				$columns = array_filter(array_map('trim', $columns));
				if(count($columns)) $lister->columns = $columns;
			}
		}

		$out .= $lister->execute();

		// Add late JS
		$info = $this->getModuleInfo();
		$version = $info['version'];
		$config->scripts->add($config->urls->{$this} . "{$this}Late.js?v={$version}");

		return $out;
	}

	/**
	 * Equivalent of ProcessPageListerPro::executeViewport
	 */
	public function executeViewport($exit = true) {
		return $this->lister->executeViewport($exit);
	}

	/**
	 * Equivalent of ProcessPageListerPro::executeActions
	 */
	public function ___executeActions() {
		$actions = new ListerProActions($this->lister);
		return $actions->execute();
	}

	/**
	 * Encodes the given data with base64, and returns a URL-safe string
	 *
	 * @param string $str
	 * @return string
	 */
	public function urlSafeBase64Encode($str) {
		return strtr(base64_encode(urlencode($str)), ['+' => '-', '/' => '_', '=' => '']);
	}

	/**
	 * Decodes a URL-safe base64 encoded string
	 *
	 * @param string $str
	 * @param bool $strict
	 * @return string
	 */
	function urlSafeBase64Decode($str, $strict = false) {
		return urldecode(base64_decode(strtr($str, '-_', '+/'), $strict));
	}

	/**
	 * Output JSON list of navigation items (bookmarks)
	 *
	 * @param array $options
	 * @return array|string
	 *
	 */
	public function ___executeNavJSON(array $options = array()) {
		$options['add'] = null;
		if(!$this->bookmarks) return parent::___executeNavJSON($options);
		$options['items'] = [];
		$i = 0;
		$bookmarks = explode("\n", str_replace("\r", "", $this->bookmarks));
		foreach($bookmarks as $line) {
			$pieces = explode(':', $line, 2);
			if(count($pieces) !== 2) continue;
			$options['items'][$i]['id'] = $this->urlSafeBase64Encode($pieces[1]);
			$options['items'][$i]['label'] = $pieces[0];
			$i++;
		}
		$options['icon'] = 'search';
		$options['itemLabel'] = 'label';
		$options['edit'] = '?bm={id}';
		$options['sort'] = false;
		return parent::___executeNavJSON($options);
	}

	/**
	 * Config inputfields
	 *
	 * @param InputfieldWrapper $inputfields
	 */
	public function getModuleConfigInputfields($inputfields) {
		$modules = $this->wire()->modules;

		/* @var InputfieldTextarea $f */
		$f = $modules->get('InputfieldTextarea');
		$f_name = 'bookmarks';
		$f->name = $f_name;
		$f->label = $this->_('Bookmarks');
		$f->description = $this->_('Enter bookmarks in the format **label:selector:columns**, one per line. The columns part is optional. For your convenience you can copy/paste a bookmark string from the note at the bottom of the Lister Selector results.');
		$f->description .= "\n" . $this->_('Example bookmark') . "...\n";
		$f->description .= $this->_('Your label') . ':template=basic-page:title,parent,modified';
		$f->icon = 'bookmark';
		$f->value = $this->$f_name;
		$inputfields->add($f);

		if($modules->isInstalled('ProcessPageListerPro')) {

			/* @var InputfieldFieldset $fieldset */
			$fieldset = $modules->get('InputfieldFieldset');
			$fieldset->label = $this->_('How should the VIEW and EDIT links work?');
			$fieldset->description = $this->_('View or edit links only appear on a page when the user has access to view or edit access to it.');
			$fieldset->icon = 'random';
			$inputfields->add($fieldset);

			$modeOptions = [
				ProcessPageLister::windowModeNone => $this->_('Same window'),
				ProcessPageLister::windowModeModal => $this->_('Modal window'),
				ProcessPageLister::windowModeBlank => $this->_('New window'),
			];

			/* @var InputfieldRadios $f */
			$f = $modules->get('InputfieldRadios');
			$f_name = 'view_mode';
			$f->name = $f_name;
			$f->label = $this->_('View links open in ...');
			$f->addOptions($modeOptions);
			$f->addOption(ProcessPageLister::windowModeHide, $this->_('Do not show view links'));
			$f->value = $this->$f_name;
			$f->columnWidth = 50;
			$fieldset->add($f);

			$f = $modules->get('InputfieldRadios');
			$f_name = 'edit_mode';
			$f->name = $f_name;
			$f->label = $this->_('Edit links open in ...');
			$f->addOptions($modeOptions);
			$f->addOption(ProcessPageLister::windowModeHide, $this->_('Do not show edit links'));
			$f->value = $this->$f_name;
			$f->columnWidth = 50;
			$fieldset->add($f);

			/* @var InputfieldCheckboxes $f */
			$f = $modules->get('InputfieldCheckboxes');
			$f_name = 'enabled_actions';
			$f->name = $f_name;
			$f->label = $this->_('Enabled actions');
			$f->icon = 'tasks';
			$options = [];
			foreach($modules as $module) {
				$class_name = $module->className();
				$parents = wireClassParents($class_name);
				if(!in_array('PageAction', $parents)) continue;
				$info = $modules->getModuleInfo($module);
				$options[$module->className()] = $info['title'];

			}
			ksort($options);
			$f->addOptions($options);
			$f->value = $this->$f_name;
			if(!$options) {
				$f->collapsed = Inputfield::collapsedYes;
				$f->notes = $this->_('No ListerPro action modules are installed.');
			}
			$inputfields->add($f);

		}
	}

}
